Header harmony
taskany-inc/bricks pull request #1213
Opened 2024-12-05 09:00 UTC by Katrin-kudryash

## PR includes

- [ ] Feature

## Related issues

Resolve #1212

2024-12-26 12:12 UTC, tsumo approved these changes

2024-12-27 07:39 UTC, Katrin-kudryash commented
/canary

2024-12-27 10:55 UTC, LamaEats requested changes

2024-12-27 10:55 UTC, LamaEats commented on src/harmony/Header/Header.tsx
> +        <a className={cn(s.HeaderNavLink, className)} {...props}>
You can use the `Link` component instead of plain html `a` element

2024-12-27 17:09 UTC, LamaEats approved these changes

2024-12-28 07:33 UTC, Katrin-kudryash commented
/create

2024-12-28 07:36 UTC, Katrin-kudryash commented
/canary

2025-01-13 07:57 UTC, merged