Offline detector
taskany-inc/bricks pull request #174
Opened 2023-06-08 19:33 UTC by Katrin-kudryash

Resolve #118

2023-06-08 19:41 UTC, Katrin-kudryash commented
Resolve #118

2023-06-08 21:01 UTC, tsumo commented on src/stories/Header.stories.tsx
> +                <>
Unnecessary fragment. Is this autoformatting?

2023-06-08 21:01 UTC, tsumo commented on tsconfig.json
> +  "include": ["src", "custom-window.d.ts"]
Duplicate "include" key

2023-06-09 07:09 UTC, tsumo commented on src/offline.tsx
> +            fetch('/')
Better yet, let's turn them into an arguments for the hook
```ts
useOfflineDetector(url: string, delay = 5000)
```

2023-06-09 09:05 UTC, 9teen90nine commented on src/offline.tsx
> +const POLLING_URL = 5000;
looks like constant name is misplaced

2023-06-15 10:26 UTC, tsumo commented on tsconfig.json
> +  "include": ["src", "custom-window.d.ts"],
Don't need this

2023-06-15 10:27 UTC, awinogradov requested changes

2023-06-15 10:27 UTC, awinogradov commented on src/hooks/useOfflineDetector.tsx
> +    const [onlineGlobal, setOnlineGlobal] = useState<boolean>(true);
Type will be provided automatically because you set default value. `<boolean>` is unnecessary here.

2023-06-15 10:27 UTC, awinogradov commented on custom-window.d.ts
> +        offlineDetector: any;
Why we need it? I don't see any calls to it in code below.

2023-06-15 10:27 UTC, awinogradov commented on src/hooks/useOfflineDetector.tsx
> +const POLLING_DELAY = 5000;
I think it would be better to have possibility to customize this interval via `UseOfflineDetectorParams`.

2023-06-15 12:10 UTC, awinogradov commented on src/hooks/useOfflineDetector.tsx
> +    /** General status */
This is not critical, but as recommendation this part of code may be changed to code with obvious names of variables without useless comments. Ex:

```ts
export const useOfflineDetector = ({ setStatus, pollingDelay = 5000, remoteServerUrl = '/' }: UseOfflineDetectorParams) => {
    const [globalOnlineStatus, setGlobalOnlineStatus] = useState(true);
    const [remoteServerStatus, setRemoteServerStatus] = useState(true);
    const remoteServerPollingInProgress = useRef(true);
    
    // ...
    
    (() => {
         if (!remoteServerPollingInProgress.current) return;
         //...
    })(); 
    
    // ...
```

2023-06-15 12:27 UTC, awinogradov requested changes
I'm recommend to check code before review ;)

2023-06-15 12:27 UTC, awinogradov commented on src/hooks/useOfflineDetector.tsx
> +            if (remoteServerPollingInProgress.current) {
`if (!remoteServerPollingInProgress.current) {`

2023-06-15 12:27 UTC, awinogradov commented on src/hooks/useOfflineDetector.tsx
> +    pollingUrl: string;
`remoteServerUrl`

2023-06-15 12:27 UTC, awinogradov commented on src/hooks/useOfflineDetector.tsx
> +            remoteServerPollingInProgress.current = true;
`remoteServerPollingInProgress.current = false;`

2023-06-15 13:16 UTC, tsumo approved these changes

2023-06-15 13:16 UTC, Katrin-kudryash commented on src/hooks/useOfflineDetector.tsx
> +            remoteServerPollingInProgress.current = true;
🤦‍♀️

2023-06-15 13:17 UTC, Katrin-kudryash commented on src/hooks/useOfflineDetector.tsx
> +    pollingUrl: string;
🤦‍♀️

2023-06-15 13:23 UTC, awinogradov commented
https://github.com/taskany-inc/issues/blob/main/CONTRIBUTING.md#sending-a-pull-request

> Make sure PR title equal with issue title w/o issue id;

2023-06-15 13:38 UTC, awinogradov approved these changes

2023-06-15 13:42 UTC, merged