Autogenerated avatars for users w/o image field
taskany-inc/bricks pull request #334
Opened 2023-08-11 09:26 UTC by DenisVorop

## PR includes
- [x] Feature

## Related issues
Resolve #333 

## QA Instructions, Screenshots, Reco

<img width="963" alt="Снимок экрана 2023-08-11 в 07 13 09" src="https://github.com/taskany-inc/bricks/assets/95316053/063db5ee-18fb-466c-8804-9425bbd2965a">

2023-08-11 12:16 UTC, awinogradov commented on src/components/Gravatar.tsx
> +                    src="/anonymous.png"
I think you can remove it

2023-08-14 11:57 UTC, DenisVorop commented
<img width="720" alt="Снимок экрана 2023-08-14 в 12 25 44" src="https://github.com/taskany-inc/bricks/assets/95316053/06fd08ac-976d-481f-beca-722256e71b25">
<img width="442" alt="Снимок экрана 2023-08-14 в 12 30 08" src="https://github.com/taskany-inc/bricks/assets/95316053/d6749737-6b79-4674-a290-23c1e24d4a0b">

2023-08-14 11:58 UTC, DenisVorop commented
<img width="720" alt="Снимок экрана 2023-08-14 в 12 25 44" src="https://github.com/taskany-inc/bricks/assets/95316053/eb132268-a625-45f3-81ec-78ce849ac376">
<img width="440" alt="Снимок экрана 2023-08-14 в 12 30 08" src="https://github.com/taskany-inc/bricks/assets/95316053/095b69f2-b0a5-46cf-baea-394e68f8aba5">

2023-08-14 13:24 UTC, awinogradov commented on src/components/Gravatar.tsx
> +    return `${arr.at(-2)?.[0] || ''} ${arr.at(-1)?.[0] || ''}`;
`arr[0]?.[0]`

2023-08-14 13:29 UTC, awinogradov requested changes
<img width="532" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/8d7bf27e-b039-4cbc-b110-0126d6bbe293">

Must be removed

2023-08-15 14:18 UTC, awinogradov requested changes

2023-08-15 14:18 UTC, awinogradov commented on src/components/UserPic.tsx
> -        currentTarget.src = '/anonymous.png';
Why here we do nothing on error, but [here](https://github.com/taskany-inc/bricks/pull/334/files#diff-fc4e5466b03ed2b606adb7ab361ba653733fa7f0580d9c97b73126580d0dbb30R93) we are using Circle as fallback?

2023-08-16 08:52 UTC, 9teen90nine approved these changes

2023-08-16 11:19 UTC, merged