Harmony: Buttons
taskany-inc/bricks pull request #639
Opened 2023-11-28 15:41 UTC by DenisVorop

## PR includes

- [x] Feature

## Related issues

Resolve #623 

## QA Instructions, Screenshots, Recordings
  
<img width="523" alt="Снимок экрана 2023-11-28 в 18 30 19" src="https://github.com/taskany-inc/bricks/assets/95316053/e01dc55b-1b5f-4d94-b7ac-e35ee5bf7496">

2023-12-05 08:39 UTC, 9teen90nine commented on src/harmony/Button/Button.module.css
> +    font-size: 13px;
could we move font-sizes to variables? Otherwise it will be copied a million times

2023-12-11 13:32 UTC, awinogradov requested changes

2023-12-11 13:32 UTC, awinogradov commented on src/harmony/Button/Button.module.css
> +.button + .button {
`.button_brick + .button_brick`

2023-12-11 13:32 UTC, awinogradov commented on src/harmony/Button/Button.module.css
> +.button:has(.icon__right) {
`.button_icon_right`

2023-12-11 13:32 UTC, awinogradov commented on src/harmony/Button/Button.module.css
> +.size__xs:has(.icon__single) {
`.button_size_xs.button_icon_right`

2023-12-12 09:35 UTC, DenisVorop commented
https://github.com/taskany-inc/bricks/assets/95316053/accfa373-6909-4d7e-84e7-fc2d2bf4a907

2023-12-12 10:20 UTC, awinogradov commented on src/harmony/Button/Button.module.css
> +.Button_brick + .Button_brick {
`.Button[class^="Button_brick"] + .Button[class^="Button_brick"] {}` allows u not to add extra class. https://www.w3schools.com/css/css_attribute_selectors.asp

2023-12-12 13:42 UTC, awinogradov approved these changes

2023-12-14 09:31 UTC, 9teen90nine approved these changes

2023-12-14 12:09 UTC, merged