Harmony: Popup
taskany-inc/bricks pull request #697
Opened 2023-12-28 12:18 UTC by DenisVorop

## PR includes

- [x] Feature

## Related issues

Resolve #668 

## QA Instructions, Screenshots, Recordings
  
### POpups

<img width="1239" alt="Снимок экрана 2023-12-28 в 15 15 31" src="https://github.com/taskany-inc/bricks/assets/95316053/5fe947ca-be17-4096-9239-a3f0d73d63a6">

### Tooltips

<img width="1238" alt="Снимок экрана 2023-12-28 в 15 15 38" src="https://github.com/taskany-inc/bricks/assets/95316053/3574f6b9-3069-45e1-b881-acecfebf2adc">

### Tooltips view 

<img width="1238" alt="Снимок экрана 2023-12-28 в 15 15 53" src="https://github.com/taskany-inc/bricks/assets/95316053/29d30b74-1052-4a17-ab82-442abbce004d">

2023-12-28 16:05 UTC, awinogradov requested changes

2023-12-28 16:05 UTC, awinogradov commented on src/harmony/Popup/Popup.tsx
> +                {arrow && <div className={s.PopupArrow} data-popper-arrow />}
nullable

2023-12-28 16:05 UTC, awinogradov commented on src/harmony/Popup/Popup.tsx
> +                style={{ minWidth, maxWidth }}
memo

2023-12-28 16:05 UTC, awinogradov commented on src/harmony/Popup/Popup.tsx
> +                <div className={s.PopupContent} style={{ maxWidth }}>
memo

2023-12-28 16:05 UTC, awinogradov commented on src/harmony/Popup/Popup.tsx
> +        popperOptions={{
memo

2023-12-29 17:14 UTC, awinogradov approved these changes

2024-01-09 12:57 UTC, 9teen90nine approved these changes

2024-01-09 13:38 UTC, merged