Harmony: Autocomplete
taskany-inc/bricks pull request #698
Opened 2023-12-28 16:51 UTC by LamaEats

... and related components and fixes

## PR includes

- [x] Bug Fix
- [x] Feature

## Related issues

Resolve #669 

## QA Instructions, Screenshots, Recordings
  
In this pr includes the same implementation of early create components

2023-12-29 17:12 UTC, awinogradov requested changes

2023-12-29 17:12 UTC, awinogradov commented on src/harmony/AutoComplete/AutoComplete.tsx
> +                            <span>{item.title}</span>
Do we really need span here?

2023-12-29 17:12 UTC, awinogradov commented on src/harmony/RadioGroup/RadioGroup.tsx
> +import React, { HTMLAttributes, PropsWithChildren, createContext, useCallback, useId } from 'react';
useCallback is never used

2023-12-29 17:12 UTC, awinogradov commented on src/harmony/RadioGroup/RadioGroup.tsx
> +                <RadioContext.Provider value={{ id: `${id}-${name}`, value, onChange, name, disabled }}>
memo

2024-01-09 11:26 UTC, LamaEats commented on src/harmony/AutoComplete/AutoComplete.tsx
> +                            <span>{item.title}</span>
Perhaps, don't needed

2024-01-13 11:12 UTC, awinogradov requested changes

2024-01-13 11:12 UTC, awinogradov commented on src/harmony/AutoComplete/AutoComplete.tsx
> +import { RadioControl as Radio, RadioGroup, RadioGroupLabel, RadioLabel } from '../RadioGroup/RadioGroup';
'RadioLabel' is defined but never used

2024-01-13 11:12 UTC, awinogradov commented on src/harmony/AutoComplete/AutoComplete.tsx
> +    checked: boolean;
optional?

2024-01-13 11:12 UTC, awinogradov commented on src/harmony/Checkbox/Checkbox.tsx
> +                onChange={onChange}
onChange, name, disabled are exist in rest

2024-01-13 11:12 UTC, awinogradov commented on src/harmony/Radio/Radio.tsx
> +                onChange={onChange}
Same comment with Checkbox

2024-01-13 11:12 UTC, awinogradov commented on src/harmony/RadioGroup/RadioGroup.tsx
> +            name={name}
Same comment with Checkbox and Radio

2024-01-17 07:58 UTC, awinogradov commented on src/harmony/AutoComplete/AutoComplete.tsx
> +        throw new Error("Don't use before initialization or outse of `AutoComplete` component");
outse -> outside

2024-01-17 07:59 UTC, awinogradov approved these changes

2024-01-17 08:00 UTC, awinogradov requested changes
RadioGroup not fixed

2024-01-18 15:25 UTC, LamaEats commented on src/harmony/AutoComplete/AutoComplete.stories.tsx
> +// };
for this https://taskany-inc.github.io/bricks/?path=/story/autocomplete--multiple-with-table
but harmony lib haven't Table components now

2024-01-19 07:06 UTC, 9teen90nine approved these changes

2024-01-19 10:15 UTC, merged