Dropdown p1: Triggers
taskany-inc/bricks pull request #720
Opened 2024-01-16 07:36 UTC by LamaEats

This pr is include some new components like Text, Label w/ icons, State, User

## PR includes

- [x] Feature

## Related issues

Resolve #674 

## QA Instructions, Screenshots, Recordings
 

<img width="441" alt="image" src="https://github.com/taskany-inc/bricks/assets/7002692/ef51deda-9361-462d-a467-54455c92cc04">
<img width="441" alt="image" src="https://github.com/taskany-inc/bricks/assets/7002692/1fbfedc4-ed16-47de-aba4-6982216128e4">
<img width="441" alt="image" src="https://github.com/taskany-inc/bricks/assets/7002692/6b8f9602-152e-43ce-b83b-c966addfdc47">
<img width="441" alt="image" src="https://github.com/taskany-inc/bricks/assets/7002692/10847f8c-31fe-4033-a184-255f824677e3">
<img width="441" alt="image" src="https://github.com/taskany-inc/bricks/assets/7002692/7436bf87-abf5-43f0-9351-cf3ffbfe319d">

2024-01-17 11:43 UTC, awinogradov requested changes

2024-01-17 11:43 UTC, awinogradov commented on src/harmony/Label/Label.tsx
> +        <Text className={cn(classes.Label, className)} class as="span" weight="bold" {...rest}>
check attrs ;)

2024-01-17 11:43 UTC, awinogradov commented on src/harmony/Label/Label.tsx
> +export const Label: React.FC<LabelProps> = ({ iconLeft, iconRight, text, className, ...rest }) => {
This is not form label. This is Badge currently, right?

2024-01-18 12:46 UTC, 9teen90nine approved these changes

2024-01-18 15:27 UTC, merged