Harmony: Table
taskany-inc/bricks pull request #749
Opened 2024-01-24 13:50 UTC by DenisVorop

## PR includes

- [x] Bug Fix
- [x] Feature

## Related issues

Resolve #748 
Related issues https://github.com/taskany-inc/issues/pull/2228

## QA Instructions, Screenshots, Recordings

<img width="994" alt="Снимок экрана 2024-01-29 в 18 00 52" src="https://github.com/taskany-inc/bricks/assets/95316053/7a8b1027-ad47-412b-98ec-93038085b1a7">

<img width="1024" alt="Снимок экрана 2024-01-29 в 18 01 17" src="https://github.com/taskany-inc/bricks/assets/95316053/9acc8928-ec0a-493e-a877-28c38094dafc">

### Collapsible table
<img width="1024" alt="Снимок экрана 2024-01-29 в 18 01 35" src="https://github.com/taskany-inc/bricks/assets/95316053/4eb9b17c-3b3d-4317-ac19-50d4426680d5">

2024-01-24 13:51 UTC, DenisVorop commented
/canary

2024-01-24 14:40 UTC, DenisVorop commented
/canary

2024-01-29 09:17 UTC, DenisVorop commented
/canary

2024-01-29 09:41 UTC, awinogradov requested changes

2024-01-29 09:41 UTC, awinogradov commented on src/harmony/index.ts
> +export * from './AutoComplete/AutoComplete';
Unnecessary diff

2024-01-29 09:41 UTC, awinogradov commented on src/harmony/Table/Table.stories.tsx
> +                        {row.map(({ render, name, style, width, item, head: _, ...rest }, index) => (
Unused variable

2024-01-30 09:19 UTC, LamaEats approved these changes

2024-01-30 09:19 UTC, LamaEats commented on src/harmony/Table/Table.module.css
> +    width: var(--table-cell-width);
Add fallback for variable value, ex. `auto` or `unset`

2024-01-30 10:01 UTC, awinogradov approved these changes

2024-01-31 09:17 UTC, merged