fix(ListView): navigation between multiple lists
taskany-inc/bricks pull request #753
Opened 2024-01-26 17:23 UTC by asabotovich

## PR includes

- [x] Bug Fix

## Related issues

Resolve: #752 

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/bricks/assets/9020793/6e923a75-3f9e-4c53-8c36-087f0a407542

2024-01-26 17:30 UTC, asabotovich commented
/canary

2024-01-26 19:15 UTC, asabotovich commented
/canary

2024-01-30 21:32 UTC, asabotovich commented
/canary

2024-01-31 09:31 UTC, awinogradov requested changes

2024-01-31 09:31 UTC, awinogradov commented on src/hooks/useKeyPress.tsx
> +export const useKeyPress = (targetKey: string, enabled = true) => {
Use if statement in place of usage instead of this argument

2024-02-01 12:58 UTC, awinogradov approved these changes

2024-02-01 13:17 UTC, tsumo approved these changes

2024-02-01 13:20 UTC, merged