Worker function from @taskany/issues for reuse
taskany-inc/bricks pull request #777
Opened 2024-01-31 17:34 UTC by nyet-ty

Resolve #765

## PR includes

- [x] Feature

2024-01-31 19:05 UTC, awinogradov requested changes

2024-01-31 19:05 UTC, awinogradov commented on src/utils/worker.ts
> +    delay: number | null;
Use optional operator instead. Required null? No way.

2024-02-01 09:13 UTC, 9teen90nine requested changes

2024-02-01 09:13 UTC, 9teen90nine commented on src/utils/worker.ts
> +    resolve: { [key: string]: (args: any) => any },
add a comment to disable warning or change to unknown

2024-02-01 09:13 UTC, 9teen90nine commented on src/utils/worker.ts
> +        console.error(error.message);
there should be onError callback

2024-02-01 11:32 UTC, awinogradov requested changes
It would be nice to have some example of usage in JSDoc or md

2024-02-01 15:58 UTC, 9teen90nine commented on docs/workerExample.md
> +const onQueeTooLong = // what to do if quee too long
queue

2024-02-01 16:00 UTC, 9teen90nine commented on src/utils/worker.ts
> +        onError(error.message);
better to forward full error, not just the message.

2024-02-01 16:22 UTC, 9teen90nine approved these changes

2024-02-01 16:48 UTC, awinogradov approved these changes

2024-02-02 09:18 UTC, merged