Process not exit while storybook build
taskany-inc/bricks pull request #781
Opened 2024-02-01 12:57 UTC by DenisVorop

## PR includes

- [x] Bug Fix

## Related issues

Resolve #780

2024-02-01 13:04 UTC, awinogradov requested changes
<img width="285" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/2d756d9b-282a-47d1-a761-1ee635f22e2d">

Lets try to find better place than root of project

2024-02-01 16:49 UTC, awinogradov requested changes

2024-02-01 16:49 UTC, awinogradov commented on .storybook/main.ts
> +import { exitProcessPlugin } from '../plugins/exitProcessPlugin';
`.vite/plugins/exitProcess`

2024-02-02 11:17 UTC, awinogradov approved these changes

2024-02-02 11:19 UTC, 9teen90nine approved these changes

2024-02-02 11:29 UTC, merged