Harmony: Offline bar component
taskany-inc/bricks pull request #823
Opened 2024-02-07 15:19 UTC by Katrin-kudryash

## PR includes

- [ ] Feature

## Related issues

Resolve #806

2024-02-07 17:17 UTC, Katrin-kudryash commented
/canary

2024-02-07 17:56 UTC, Katrin-kudryash commented
/canary

2024-02-07 19:07 UTC, Katrin-kudryash commented
/canary

2024-02-07 20:24 UTC, Katrin-kudryash commented
/canary

2024-02-14 19:56 UTC, Katrin-kudryash commented
/canary

2024-02-15 11:17 UTC, asabotovich approved these changes

2024-02-15 11:21 UTC, awinogradov requested changes

2024-02-15 11:21 UTC, awinogradov commented on src/harmony/OfflineBanner/OfflineBanner.tsx
> +    return <Alert view={'danger'} text={description} className={s.Alert} />;
Smbdy need help u with formatting ;)

2024-02-15 12:47 UTC, awinogradov commented on src/harmony/OfflineBanner/OfflineBanner.tsx
> +    description: string;
description > text

2024-02-15 13:47 UTC, Katrin-kudryash commented
/canaru

2024-02-15 13:48 UTC, Katrin-kudryash commented
/canary

2024-02-15 14:41 UTC, Katrin-kudryash commented
<img width="1586" alt="Untitled 12" src="https://github.com/taskany-inc/bricks/assets/81121562/0326ad59-57a2-4ce0-80db-377b371ff77b">

2024-02-15 16:18 UTC, awinogradov approved these changes

2024-02-15 16:20 UTC, tsumo approved these changes

2024-02-15 16:22 UTC, merged