Harmony: MenuItem
taskany-inc/bricks pull request #865
Opened 2024-02-15 12:25 UTC by DenisVorop

## PR includes

- [x] Bug Fix
- [x] Feature

## Related issues

Resolve #864 

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/bricks/assets/95316053/f31fd8a3-02fd-485e-9d89-8b9f9b1e1588

2024-02-15 12:26 UTC, DenisVorop commented
/canary

2024-02-17 12:42 UTC, DenisVorop commented
/canary

2024-02-18 15:24 UTC, DenisVorop commented
/canary

2024-02-18 15:30 UTC, DenisVorop commented
/canary

2024-02-19 08:58 UTC, DenisVorop commented
/canary

2024-02-19 11:34 UTC, DenisVorop commented
/canary

2024-02-20 07:41 UTC, DenisVorop commented on src/harmony/Input/Input.tsx
> +                { '--input-width': (typeof width === 'string' ? width : `${width}px`) || 'unset' },
I used this approach to ensure that the cascade works. If the width is set as an inline style, it cannot be modified using the class

2024-02-20 09:24 UTC, awinogradov requested changes

2024-02-20 09:24 UTC, awinogradov commented on src/harmony/Input/Input.module.css
> +    pointer-events: var(--pointer-events, auto);
`--input-pointer-events`

2024-02-20 09:24 UTC, awinogradov commented on src/harmony/DatePicker/DatePicker.tsx
> +                                    width="100%"
Why not to do it via DatePicker css?

2024-02-20 09:24 UTC, awinogradov commented on src/harmony/DatePicker/DatePicker.tsx
> +        [quarters[0]]: `date-picker-quarter-${quarters[0]}`,
`Q1: 'date-picker-quarter-Q1'`

2024-02-20 10:33 UTC, awinogradov approved these changes

2024-02-20 10:43 UTC, asabotovich approved these changes

2024-02-20 11:11 UTC, merged