Harmony: update Dropdown
taskany-inc/bricks pull request #895
Opened 2024-02-22 11:29 UTC by DenisVorop

## PR includes

- [ ] Bug Fix
- [ ] Docs
- [ ] Specs
- [ ] Refactor
- [ ] Feature
- [ ] DX
- [ ] DevOps

## Related issues

Resolve #<issue>

Related issues #<issue>, #<issue>

## QA Instructions, Screenshots, Recordings
  
_Please replace this line with instructions on how to test your changes, a note on the devices and browsers this has been tested on, as well as any relevant images for UI changes._

2024-02-22 11:29 UTC, DenisVorop commented
/canary

2024-02-22 11:52 UTC, DenisVorop commented
/canary

2024-02-22 12:32 UTC, DenisVorop commented
/canary

2024-02-24 22:19 UTC, awinogradov requested changes

2024-02-24 22:19 UTC, awinogradov commented on src/harmony/Dropdown/Dropdown.module.css
> +    gap: 0.125rem;
Magic?

2024-02-24 22:19 UTC, awinogradov commented on src/harmony/Dropdown/Dropdown.module.css
> +    height: 50px;
Magic?

2024-02-24 22:19 UTC, awinogradov commented on src/harmony/Dropdown/Dropdown.module.css
> +.DropdownTrigger_error.DropdownTrigger_error,
Why double selectors here?

2024-02-24 22:19 UTC, awinogradov commented on src/harmony/Dropdown/Dropdown.module.css
> +.DropdownTriggerLabel_error.DropdownTriggerLabel_error {
Why?

2024-02-26 08:32 UTC, DenisVorop commented on src/harmony/Dropdown/Dropdown.module.css
> +    gap: 0.125rem;
https://github.com/taskany-inc/bricks/pull/895/files#diff-e328df8cd570b3353fbf60af1ce32eae6bef2c0f266b555ca8d030d0677d2b0eR6-R8

2024-02-26 08:32 UTC, DenisVorop commented on src/harmony/Dropdown/Dropdown.module.css
> +    height: 50px;
https://github.com/taskany-inc/bricks/pull/895/files#diff-e328df8cd570b3353fbf60af1ce32eae6bef2c0f266b555ca8d030d0677d2b0eR28-R31

2024-02-26 08:33 UTC, DenisVorop commented
/canary

2024-02-26 12:48 UTC, asabotovich approved these changes

2024-02-26 12:49 UTC, asabotovich commented on src/harmony/Dropdown/Dropdown.stories.tsx
> +const Dropdownnn = ({ view, error }: any) => {
any

2024-02-26 13:26 UTC, awinogradov requested changes

2024-02-26 13:26 UTC, awinogradov commented on src/harmony/Dropdown/Dropdown.stories.tsx
> +const style = { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20 };
Gotcha!

<img width="480" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/4cb7f9db-0366-43c7-a259-1f69f69f5d11">

2024-02-26 13:29 UTC, DenisVorop commented on src/harmony/Dropdown/Dropdown.stories.tsx
> +const style = { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20 };
my apologies

2024-02-26 13:31 UTC, awinogradov approved these changes

2024-02-26 13:37 UTC, merged