Harmony: Activity feed with history items
taskany-inc/bricks pull request #935
Opened 2024-03-05 18:15 UTC by LamaEats

## PR includes

- [x] Feature

## Related issues

Resolve #814 

## QA Instructions, Screenshots, Recordings
  
<img width="397" alt="image" src="https://github.com/taskany-inc/bricks/assets/7002692/7ffe8246-b3e7-4af1-acc7-02cca357f482">
<img width="397" alt="image" src="https://github.com/taskany-inc/bricks/assets/7002692/624f2834-bcd2-47a9-992b-3d87c618b3a0">
<img width="397" alt="image" src="https://github.com/taskany-inc/bricks/assets/7002692/4ccd4995-d4af-44dd-ac18-5d499f05afdf">

2024-03-06 12:00 UTC, awinogradov requested changes

2024-03-06 12:00 UTC, awinogradov commented on src/harmony/User/User.module.css
> +
Does it makes sense?

2024-03-06 12:00 UTC, awinogradov commented on src/harmony/User/User.tsx
> +    size?: 's' | 'm';
`keyof typeof sizeMap` ?

2024-03-11 09:32 UTC, awinogradov requested changes

2024-03-11 09:32 UTC, awinogradov commented on src/harmony/HistoryRecord/HistoryRecord.tsx
> +import React, { useCallback, useEffect, useMemo, useReducer, useRef, useState } from 'react';
<img width="414" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/d925047f-46ea-4299-b389-89fa1d9a2712">

2024-03-12 09:01 UTC, LamaEats commented on src/harmony/HistoryRecord/HistoryRecord.tsx
> +import React, { useCallback, useEffect, useMemo, useReducer, useRef, useState } from 'react';
sorry, i'm blind

2024-03-12 09:15 UTC, awinogradov approved these changes

2024-03-12 09:16 UTC, merged