Harmony: StateGroup
taskany-inc/bricks pull request #955
Opened 2024-03-11 17:05 UTC by DenisVorop

## PR includes

- [x] Feature

## Related issues

Resolve #954 

Related issues: 
- https://github.com/taskany-inc/issues/pull/2419

## QA Instructions, Screenshots, Recordings
  
<img width="137" alt="Снимок экрана 2024-03-11 в 17 44 09" src="https://github.com/taskany-inc/bricks/assets/95316053/5d33899f-2310-44dd-a5f7-48efe73c58c2">
<img width="137" alt="Снимок экрана 2024-03-11 в 17 44 13" src="https://github.com/taskany-inc/bricks/assets/95316053/d6339857-aa10-44ae-851a-537845f5fd35">

2024-03-11 17:06 UTC, DenisVorop commented
/canary

2024-03-12 06:54 UTC, DenisVorop commented
/canary

2024-03-12 09:19 UTC, awinogradov requested changes
We have same code for UserGroup component. It would be better to create meta component and use it in UserGroup, StateGroup and etc.

2024-03-12 13:53 UTC, DenisVorop commented
<img width="160" alt="Снимок экрана 2024-03-12 в 16 43 11" src="https://github.com/taskany-inc/bricks/assets/95316053/226f0018-f407-4481-bd7f-5dfd3ce7a971">

2024-03-12 14:03 UTC, awinogradov requested changes

2024-03-12 14:03 UTC, awinogradov commented on src/harmony/Group/Group.module.css
> +.Group_hovered .GroupItem:hover {
`.Group_interactive .GroupItem:hover`

2024-03-12 14:03 UTC, awinogradov commented on src/harmony/Group/Group.tsx
> +    withHover?: boolean;
`interactive` to be consistent with same behaviour in other components

2024-03-13 08:38 UTC, awinogradov approved these changes

2024-03-13 14:32 UTC, merged